### ISSUE TITLE
Governance Stake Vote not working for Whale

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#816]
**Describe the bug**
A whale who currently has their XCUR staked, cannot vote. They tried uninstalling and then reinstalling the mobile app but their vote strength is still 0. 

Curate app version: 7.7.0 from the App Store. 

**Screenshots**
<img width="386" alt="image" src="https://user-images.githubusercontent.com/88379508/216567248-87ae76b3-79ec-4253-afe5-1f77b2482df8.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: Latest

**User ID**
6520c0758fbb0a95f325fc6fee0d24b5cd11
dimitrovlazar@yahoo.com

**Comment by TheMad-J-Hatter** [comment]
@eventang2015, would you please investigate as to why this user couldn't vote with stakes XCUR but I could. Thanks

**Comment by eventang2015** [comment]
@TheMad-J-Hatter  this one should be fixed. 
there was no account snapshots.

**Comment by TheMad-J-Hatter** [comment]
@eventang2015, I'm unsure what you mean by there being 'no account snapshot', please explain? This user was staking well before the snapshot was taken. 

I told him about the fix but it is still not working for him. Please advise.

![image](https://user-images.githubusercontent.com/88379508/217219870-20fb8fd2-b4f8-45a7-9b6e-f385789b8d0e.png)

**Comment by eventang2015** [comment]
https://github.com/pellartech/curate/issues/633
maybe there's no account snapshots before the propose's created date. 
let me duplicate one record for him...

**Comment by TheMad-J-Hatter** [comment]
Thank you @eventang2015, the user has just messaged me saying that he just voted successfully.

**Comment by TheMad-J-Hatter** [comment]
@eventang2015, can I confirm that the next proposal snapshot will include all accounts that are staking XCUR too?
